
apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secret           # A unique name for this Secret.

type: Opaque                      # 'Opaque' is a generic type for arbitrary user-defined data.

data:
  GEMINI_API_KEY: "YOUR_BASE64_ENCODED_GEMINI_API_KEY"      # replace "YOUR_BASE64_ENCODED_GEMINI_API_KEY" with the actual Base64-encoded value.